[package]
name = "farm-extra-rewards-wrapper-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.farm-extra-rewards-wrapper]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.53.0"
default-features = false
