// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           35
// Async Callback:                       1
// Total number of exported functions:  38

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    farm_extra_rewards_wrapper
    (
        init => init
        upgrade => upgrade
        getRewardPerShare => reward_per_share
        getRewardReserve => reward_reserve
        getFarmingTokenId => farming_token_id
        getRewardTokenId => reward_token_id
        getPerBlockRewardAmount => per_block_reward_amount
        getLastRewardBlockNonce => last_reward_block_nonce
        getDivisionSafetyConstant => division_safety_constant
        getUserTotalFarmPosition => user_total_farm_position
        getAllowExternalClaim => allow_external_claim
        getFarmPositionMigrationNonce => farm_position_migration_nonce
        registerFarmToken => register_farm_token
        getFarmTokenId => farm_token
        getFarmTokenSupply => farm_token_supply
        addToPauseWhitelist => add_to_pause_whitelist
        removeFromPauseWhitelist => remove_from_pause_whitelist
        pause => pause
        resume => resume
        getState => state
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        updateOwnerOrAdmin => update_owner_or_admin_endpoint
        getPermissions => permissions
        depositRewardTokens => deposit_reward_tokens
        withdrawRewardTokens => withdraw_reward_tokens
        getRewardTokens => reward_tokens
        getTokenAdditionBlock => token_addition_block
        wrapFarmToken => wrap_farm_token_endpoint
        claimRewards => claim_rewards
        unwrapFarmToken => unwrap_farm_token
        unwrapAndExitFarm => unwrap_and_exit_farm
        addFarms => add_farms
        removeFarms => remove_farms
        getFarmForFarmToken => get_farm_for_farm_token_view
        getFarmForFarmingToken => get_farm_for_farming_token_view
        getFarmConfig => get_farm_config
    )
}

multiversx_sc_wasm_adapter::async_callback! { farm_extra_rewards_wrapper }
