// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    auto_pos_creator
    (
        init => init
        addPairsToWhitelist => add_pairs_to_whitelist
        removePairsFromWhitelist => remove_pairs_from_whitelist
        createPosFromSingleToken => create_pos_from_single_token
        createPosFromTwoTokens => create_pos_from_two_tokens
        fullExitPos => full_exit_pos
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
