[package]
name = "dca-module-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dca-module]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.53.0"
default-features = false
