// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    auto_farm
    (
        depositFarmTokens
        withdrawFarmTokens
        getUserFarmTokens
        addFarms
        removeFarms
        getFarmForFarmToken
        getFarmsForFarmingToken
        getFarmConfig
    )
}

elrond_wasm_node::wasm_empty_callback! {}
