// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    auto_farm
    (
        changeProxyClaimAddress
        addFarms
        removeFarms
        getFarmForFarmToken
        getFarmsForFarmingToken
        getFarmConfig
        register
        withdrawAllAndUnregister
        depositFarmTokens
        withdrawFarmTokens
        getUserFarmTokens
        addMetastakingScs
        removeMetastakingScs
        getMetastakingScForDualYieldToken
        getMetastakingScsForLpFarmToken
        depositMetastakingTokens
        withdrawMetastakingTokens
        getUserMetastakingTokens
        getMetastakingConfig
        claimAllRewardsAndCompound
        userClaimRewards
        getUserRewards
        claimFees
        getFeePercentage
        getAccumulatedFees
        setEnergyFactoryAddress
        getEnergyFactoryAddress
    )
}

elrond_wasm_node::wasm_empty_callback! {}
