// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback (empty):               1
// Total number of exported functions:  31

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    auto_farm
    (
        changeProxyClaimAddress
        register
        withdrawAllAndUnregister
        depositFarmTokens
        withdrawAllFarmTokens
        withdrawSpecificFarmTokens
        getUserFarmTokens
        depositMetastakingTokens
        withdrawAllMetastakingTokens
        withdrawSpecificMetastakingTokens
        getUserMetastakingTokens
        claimAllRewardsAndCompound
        userClaimRewards
        getUserRewards
        claimFees
        getFeePercentage
        getAccumulatedFees
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        addFarms
        removeFarms
        getFarmForFarmToken
        getFarmForFarmingToken
        getFarmConfig
        addMetastakingScs
        removeMetastakingScs
        getMetastakingForDualYieldToken
        getMetastakingForLpFarmToken
        getMetastakingConfig
    )
}

elrond_wasm_node::wasm_empty_callback! {}
