// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           25
// Async Callback (empty):               1
// Total number of exported functions:  28

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    order_book
    (
        init => init
        upgrade => upgrade
        pause => pause_endpoint
        unpause => unpause_endpoint
        setRouterAddress => set_router_address
        setTreasuryAddress => set_treasury_address
        setPruningFee => set_pruning_fee
        setP2pProtocolFee => set_p2p_protocol_fee
        addExecutorsToWhitelist => add_executors_to_whitelist
        removeExecutorsFromWhitelist => remove_exectors_from_whitelist
        createOrder => create_order
        cancelOrder => cancel_order
        executeOrders => execute_orders
        pruneExpiredOrder => prune_expired_order
        getLastOrderId => get_last_order_id
        getOrders => get_orders
        getOrderInfo => orders
        getRouterAddress => router_address
        getTreasuryAddress => treasury_address
        getP2pProtocolFee => p2p_protocol_fee
        getPruningFee => pruning_fee
        getExecutorWhitelist => executor_whitelist
        isPaused => paused_status
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
