[package]
name = "exchange-deployer-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.exchange-deployer]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.46.1"
default-features = false
