// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    token_exposure_voting
    (
        init => init
        upgrade => upgrade
        getTokenVotes => token_votes
        getTotalVotes => total_votes
        getTokensForWeek => tokens_for_week
        getVotingTokenId => voting_token_id
        getBoostedAmount => boosted_amount
        getTotalBoostedAmount => total_boosted_amount
        vote => vote
        boost => boost
        withdrawBoostFunds => withdraw_boost_funds
        clearUserVotes => clear_user_votes
        getBoostedTokensForWeek => get_boosted_tokens_for_week
        getTokenRanking => get_token_ranking
        getWeekRanking => get_week_ranking
        getCurrentWeek => get_current_week
        getFirstWeekStartEpoch => first_week_start_epoch
        setEnergyFactoryAddress => set_energy_factory_address
        getEnergyFactoryAddress => energy_factory_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
