// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           43
// Async Callback:                       1
// Total number of exported functions:  45

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    energy_dao
    (
        registerWrappedFarmToken
        registerUnstakeFarmToken
        registerWrappedMetastakingToken
        registerUnstakeMetastakingToken
        addFarms
        removeFarms
        addMetastakingAddresses
        removeMetastakingAddresses
        getFarmState
        getFarmingTokenId
        getFarmTokenId
        getDivisionSafetyConstant
        getDualYieldTokenId
        getLpFarmTokenId
        getStakingTokenId
        getLpFarmAddress
        getStakingFarmAddress
        getWrappedFarmTokenId
        getUnstakeFarmTokenId
        getWrappedMetastakingTokenId
        getUnstakeMetastakingTokenId
        getUnbondPeriod
        getExitPenaltyPercent
        enterFarm
        claimUserRewards
        unstakeFarm
        unbondFarm
        enterMetastaking
        unstakeMetastaking
        unbondMetastaking
        claimMetastakingRewards
        lockEnergyTokens
        claimFeesCollectorRewards
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        addAdmin
        removeAdmin
        updateOwnerOrAdmin
        getPermissions
        issueWrappedToken
        setTransferRoleWrappedToken
        unsetTransferRoleWrappedToken
        getWrappedTokenId
        callBack
    )
}
