[package]
name = "order-book-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.order-book]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.60.0"
default-features = false
