// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    exchange_deployer
    (
        init => init
        upgrade => upgrade
        setActionFee => set_action_fee
        setDefaultActionFee => set_default_action_fee
        claimFees => claim_fees
        getActionFee => get_action_fee
        getFeeToken => fee_token
        setRouterAddress => set_router_address
        setRouterOwnerAddress => set_router_owner_address
        setPairSourceAddress => set_pair_source_address
        deployLiquidityPool => deploy_liquidity_pool
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
