// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           21
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    exchange_deployer
    (
        init => init
        upgrade => upgrade
        setActionFee => set_action_fee
        setDefaultActionFee => set_default_action_fee
        claimFees => claim_fees
        getActionFee => get_action_fee
        getFeeToken => fee_token
        setRouterAddress => set_router_address
        setRouterOwnerAddress => set_router_owner_address
        setPairSourceAddress => set_pair_source_address
        deployLiquidityPool => deploy_liquidity_pool
        setSimpleLockSourceAddress => set_simple_lock_source_address
        deploySimpleLock => deploy_simple_lock
        simpleLockIssueFarmProxyToken => simple_lock_issue_farm_proxy_token
        simpleLockAddFarmToWhitelist => simple_lock_add_farm_to_whitelist
        simpleLockRemoveFarmFromWhitelist => simple_lock_remove_farm_from_whitelist
        simpleLockIssueLpProxyToken => simple_lock_issue_lp_proxy_token
        simpleLockAddLpToWhitelist => simple_lock_add_lp_to_whitelist
        simpleLockRemoveLpFromWhitelist => simple_lock_remove_lp_from_whitelist
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
