// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    dca_module
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        withdraw => withdraw
        withdrawAll => withdraw_all
        getUserFunds => get_user_funds
        setNrRetries => set_nr_retries
        addTotalActions => add_total_actions
        removeTotalActions => remove_total_actions
        changeTradeFrequency => change_trade_frequency
        getActionInfo => get_action_info
        getLastActionId => action_id
        getNrRetries => nr_retries
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        promise_callback => promise_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
